name: Test de Charge Automatique

on:
  push:
    branches: [ main ]

jobs:
  check-performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer et Lancer le Backend
        run: |
          cd backend
          npm install express cors
          node server.js & 
          sleep 5 
          
      - name: Ex√©cuter le script de test
        run: node load-test.js